### ISSUE TITLE
한글 자간 관련...

### ISSUE THREAD

**Issue by junghan0611** [injae/.emacs.d#1]
;; +------------+------------+
;; | 일이삼사오 | 일이삼사오 |
;; +------------+------------+
;; | ABCDEFGHIJ | ABCDEFGHIJ |
;; +------------+------------+
;; | 1234567890 | 1234567890 |
;; +------------+------------+
;; | 일이삼사오 | 일이삼사오 |
;; | abcdefghij | abcdefghij |
;; +------------+------------+

injae님 닷파일 보고 많이 배웠습니다.
혹시 위에 테이블 잘 맞추셨나요?

VI로 열어보고 딱 맞는것 보고 놀랐습니다. 
이맥스 입문자인데... 이럴수가 싶었네요.

**Comment by injae** [comment]
이맥스에서 한글 사이즈 맞추는게 좀 노가다가 심합니다. 😢 
별다른 방법이 없어 저도 사용하고 싶은 폰트가 생기면 위에 있는 테이블을 기준으로 하나하나 변경하면서 수작업으로 맞춰서 사용합니다. 😵‍💫 
https://github.com/injae/.emacs.d/blob/c3b73fe5ac0e022312a0e11376e47939f9afb85d/config.org?plain=1#L249-L263

**Comment by junghan0611** [comment]
injae님 첫 번째 설정을 적용하니 잘 맞네요. 감사합니다.

**Comment by junghan0611** [comment]
injae님 첫 번째 설정을 적용하니 잘 맞네요. 감사합니다.^^
